spring:
  application:
    name:job

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: kenzhe
    password: kenzhe

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


# Disabling the /v3/api-docs endpoint
springdoc:
  api-docs:
    enabled: true

# Disabling the swagger-ui
  swagger-ui:
    enabled: true